### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by yueziming** [justquanyin/third-payment#2]
你好，这个怎么运行起来？

**Comment by justquanyin** [comment]
你好，文档中有示例演示该如何使用。
主要步骤是：
1. 引入 third-payment模块 
var Lib = require('third-payment');
2.使用配置文件 or 配置参数Json对象初始化类库
var obj = new Lib("./params.json"); 或者 var obj = new Lib({配置参数吧啦吧啦});
3. 根据想使用的功能调用不同的函数。如获取预支付数据 obj.getPrePay(data)

帮助link: https://www.npmjs.com/package/third-payment#使用方式

**Comment by zengleyi** [comment]
不知道作者用这个跑过支付宝支付没有

**Comment by justquanyin** [comment]
我们线上的支付系统就是用的这个包在跑的
