### ISSUE TITLE
对于支付宝来讲vendor填什么？

### ISSUE THREAD

**Issue by zengleyi** [justquanyin/third-payment#5]
对于支付宝来讲vendor填什么？

**Comment by justquanyin** [comment]
vendor是根据你配置文件中 alipay 下的key所决定的。 你配置文件中的名字是什么，就填什么。

**Comment by zengleyi** [comment]
什么意思？？alipay_web???

**Comment by justquanyin** [comment]
"alipay": {
    "app": {
      "partner": "",
      "app_id": "",
      "seller_id": "",
      "it_b_pay": "",  // 支付过期时间
      "public_key": "", // 公钥
      "private_key": "",   // 私钥
      "openali_public_key": ""  // openapi 公钥
    }
  }

如上配置文件中 ，“app” 就是你需要填的vendor字段值。 "alipay"这个值代表你使用的是支付宝， ”app“这个值指的你使用的是哪个商户配置。
对于一个通用的交易系统，产生的prepaydata，应该是根据支付方式下使用的哪个商户来返回的。
举个例子： 
比如你使用支付宝，你有支付宝商户平台A和B，当你想让用户将支付的钱入账到B账户时，B账户就是你所说的vendor，那B账户下的配置就是相应在支付宝商户平台下的应用ID和商户ID以及secret key。

**Comment by zengleyi** [comment]
if(config.alipay){
    
    for(var key in config.alipay){
      var alipay = config.alipay[key];
      if(!alipay.seller_id){
        this.setErr("支付宝: seller_id 配置错误");
        return false;
      }
      if(!alipay.partner){
        this.setErr("支付宝: partner 配置错误");
        return false;
      }
      if(!alipay.app_id){
        this.setErr("支付宝: app_id 配置错误");
        return false;
      }
    } 
  }
我用官网的资料做aplipay_web的时候，需要的只是应用私钥，支付宝公钥和app_id。seller_id是系统返回时url显示的,至于alipay.partner不知道是什么，返回的里面也没有这个参数。

**Comment by justquanyin** [comment]
支付宝文档：https://docs.open.alipay.com/59/103663/

我们用的是老的接口，没有使用新的接口，可能会有些差异。
partner的值在 支付宝商户平台下账户管理里面的PID的值。

**Comment by zengleyi** [comment]
看来这个问题在于对于支付宝的各种业务（电脑网页、手机网页、app支付）需要的必选参数是不同的，如果要把这个third-payment做好，对于业务分类处理要做好switch(case)

**Comment by justquanyin** [comment]
多谢提意见，我尽量做好兼容。
